In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\ANACONDA\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ANACONDA\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [9]:
X=X.astype(int)
X

array([[     0,      0,    619, ...,      1,      1, 101348],
       [     0,      1,    608, ...,      0,      1, 112542],
       [     0,      0,    502, ...,      1,      0, 113931],
       ...,
       [     0,      0,    709, ...,      0,      1,  42085],
       [     1,      0,    772, ...,      1,      0,  92888],
       [     0,      0,    792, ...,      1,      0,  38190]])

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(7500, 11)
(2500, 11)
(7500,)
(2500,)


In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
# Initialising the ANN
classifier = Sequential()

In [16]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [17]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
7500/7500 [==============================] - 1s 191us/step - loss: 0.4903 - accuracy: 0.7983
Epoch 2/100
7500/7500 [==============================] - 1s 116us/step - loss: 0.4190 - accuracy: 0.8175
Epoch 3/100
7500/7500 [==============================] - 1s 127us/step - loss: 0.4139 - accuracy: 0.8209
Epoch 4/100
7500/7500 [==============================] - 1s 128us/step - loss: 0.4107 - accuracy: 0.8245
Epoch 5/100
7500/7500 [==============================] - 1s 125us/step - loss: 0.4080 - accuracy: 0.8264
Epoch 6/100
7500/7500 [==============================] - 1s 130us/step - loss: 0.4062 - accuracy: 0.8288
Epoch 7/100
7500/7500 [==============================] - 1s 123us/step - loss: 0.4040 - accuracy: 0.8295
Epoch 8/100
7500/7500 [==============================] - 1s 131us/step - loss: 0.4031 - accuracy: 0.8293
Epoch 9/100
7500/7500 [==============================] - 1s 143us/step - loss: 0.4011 - accuracy: 0.8312
Epoch 10/100
7500/7500 [==============================]

7500/7500 [==============================] - 1s 154us/step - loss: 0.3336 - accuracy: 0.8637
Epoch 79/100
7500/7500 [==============================] - 1s 171us/step - loss: 0.3340 - accuracy: 0.8627
Epoch 80/100
7500/7500 [==============================] - 1s 158us/step - loss: 0.3337 - accuracy: 0.8657
Epoch 81/100
7500/7500 [==============================] - 1s 159us/step - loss: 0.3335 - accuracy: 0.8627
Epoch 82/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3327 - accuracy: 0.8645
Epoch 83/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3341 - accuracy: 0.8621
Epoch 84/100
7500/7500 [==============================] - 1s 198us/step - loss: 0.3339 - accuracy: 0.86360s - los
Epoch 85/100
7500/7500 [==============================] - 1s 170us/step - loss: 0.3335 - accuracy: 0.8635
Epoch 86/100
7500/7500 [==============================] - 1s 187us/step - loss: 0.3342 - accuracy: 0.8639
Epoch 87/100
7500/7500 [===========================

In [24]:
y_pred = classifier.predict(X_test)
y_pred

array([[0.23175211],
       [0.27856433],
       [0.15258873],
       ...,
       [0.26146084],
       [0.08645429],
       [0.04964368]], dtype=float32)

In [25]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1898,   93],
       [ 256,  253]], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score

lr_conf = confusion_matrix(y_test, y_pred)
lr_acc = accuracy_score(y_test, y_pred)
print(lr_conf)
print(lr_acc*100)

[[1898   93]
 [ 256  253]]
86.04
